### ISSUE TITLE
Lower memory load of `test_stgcn` and `test_stbln`

### ISSUE THREAD

**Issue by ad-daniel** [tasostefas/opendr_internal#167]
I think I've figured out why we've been having issues with the memory. It isn't because of running multiple in parallel (or at least, not directly). Testing it locally, during the test of `test_stgcn` my memory spikes by 6GB, with `test_stbln` it spikes by 7.2GB. Linux github action [runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) only have 7GB on ram, with this load that doesn't leave much wiggle room. It could also explain why the issue is so inconsistent as depending on what is running at the same time on those machines it might tip over.

If I'm not wrong these models were recently changed, no?

@negarhdr do you think it's possible to simplify the complexity of this test so as to be less memory hungry?

**Comment by negarhdr** [comment]
@ad-daniel 
For this tool (skeleton-based action recognition), 4 different methods are tested sequentially (tagcn, pstgcn, stgcn, and stbln) and as I remember it always starts with tagcn and ends up with stbln. I am not sure if the memory is cleared after testing each **tool** or after each ** unit test**, BTW, do you think that testing 4 methods sequentially for this tool might cause the memory spike?  maybe that's why the ram spikes for the last two methods (stgcn and stbln)!

**Comment by ad-daniel** [comment]
Unfortunately I don't think that's the issue, in fact you can see the spike just by running them separately with:
`python3 -m unittest tests/sources/tools/perception/skeleton_based_action_recognition/test_stbln.py`
![test](https://user-images.githubusercontent.com/44834743/145878471-3efe5149-adb3-4ade-87ab-974eadfaf1e9.png)

**Comment by ad-daniel** [comment]
Should be fine now.
